### PR TITLE
handle multiple fatalities from collision

### PR DESCRIPTION
**Pull request by mscarey**
Types of changes
----------------

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
- Code cleanup / Refactoring

Description
-----------

To address problems with handling bulletins that mentioned more than one fatality, I separated the functions for parsing text about people from the functions for parsing text about incidents, and put them in separate modules. Now, a record about an incident can be matched up to multiple records about people, to create one fatality record for each person.

~~And I completely broke the CLI in a way I don't understand.~~
Tests are passing and when I've tried out the CLI it looks okay.

Bulletins about multiple fatalities could only be scraped for the first fatality in the bulletin, not all of them. Also, they were more likely to create parsing errors because they had more text that the parser didn't expect.

I added a few test cases in pytest. The fatal error I created seems to be in the async code, which I don't understand how to step through or test.

Checklist:
----------

-  [x] I have updated the documentation accordingly
-  [x] I have written unit tests

Fixes: scrapd/scrapd#183

### CODE REVIEW

**Comment by mscarey** [comment]
I didn't change `/tests/features/retrieve.feature#L14` but the tests are now passing. Maybe there were no multiple-fatality collisions in 2018?

Also, I added a unique ID field but I don't know how to determine if that causes any trouble on viz.scrapd. I don't think the ID field should be displayed there, of course.

I added a test to check that both fatalities on 08/17/2019 are picked up.

**Comment by rgreinho** [comment]
Great work @mscarey!

Regarding the tests let's keep it like that. But there is definitely a problem somewhere:
1. ScrAPD counts 72 entries
2. Open Data Portal counts 73 entries
3. In the last report of 2018, APD says: `This is Austin’s 73rd fatal traffic crash of 2018, resulting in 74 fatalities this year.`

A bunch of questions/remarks before moving forward:
1. It is impossible for me to do a deep review, as all the files look new (which makes sense as you moved the content). Let's do the following:
    1. Create another branch and simply move the files around like you did here, without changing any code.
    2. We'll merge it to master
    3. Then, rebase this branch on top of master. You may have to squash it since you have so many commits. The rebase would be extremely painful otherwise.
2. What's your strategy to update the pipeline and associated tooling?
3. What's your strategy to update the dashboard?
4. Instead of updating all the tooling and having a lot of duplicated information, it would be better to simply update the structure. I don't see a good reason for a major breaking of the data structure ans surrounding tooling. If we go from this structure:
```json
{
    "Age": 36,
    "Case": "19-2291933",
    "DOB": "12/28/1982",
    "Date": "08/17/2019",
    "Ethnicity": "Black",
    "Fatal crashes this year": "50",
    "First Name": "Cedric",
    "Gender": "male",
    "ID": "19-2291933-0",
    "Last Name": "Benson",
    "Link": "http://austintexas.gov/news/traffic-fatality-50-3",
    "Location": "4500 FM 2222/Mount Bonnell Road",
    "Notes": "The preliminary investigation yielded testimony from witnesses who reported seeing the BMW motorcycle driven by Cedric Benson traveling at a high rate of speed westbound in the left lane of FM 2222. A white, 2014 Dodge van was stopped at the T-intersection of Mount Bonnell Road and FM 2222. After checking for oncoming traffic, the van attempted to turn left on to FM 2222 when it was struck by the oncoming motorcycle.\n\n\tThe driver of the van was evaluated by EMS on scene and refused transport. The passenger of the van and a bystander at the scene attempted to render aid to Mr. Benson and his passenger Aamna Najam. Cedric Benson and Aamna Najam were both pronounced on scene.\n\n\tThe van driver remained on scene and is cooperating with the ongoing investigation.\n\n\tThe family of Cedric Benson respectfully requests privacy during this difficult time and asks that media refrain from contacting them.",
    "Time": "10:20 PM"
  },
  {
    "Age": 27,
    "Case": "19-2291933",
    "DOB": "01/26/1992",
    "Date": "08/17/2019",
    "Ethnicity": "Asian",
    "Fatal crashes this year": "50",
    "First Name": "Aamna",
    "Gender": "female",
    "ID": "19-2291933-1",
    "Last Name": "Najam",
    "Link": "http://austintexas.gov/news/traffic-fatality-50-3",
    "Location": "4500 FM 2222/Mount Bonnell Road",
    "Notes": "The preliminary investigation yielded testimony from witnesses who reported seeing the BMW motorcycle driven by Cedric Benson traveling at a high rate of speed westbound in the left lane of FM 2222. A white, 2014 Dodge van was stopped at the T-intersection of Mount Bonnell Road and FM 2222. After checking for oncoming traffic, the van attempted to turn left on to FM 2222 when it was struck by the oncoming motorcycle.\n\n\tThe driver of the van was evaluated by EMS on scene and refused transport. The passenger of the van and a bystander at the scene attempted to render aid to Mr. Benson and his passenger Aamna Najam. Cedric Benson and Aamna Najam were both pronounced on scene.\n\n\tThe van driver remained on scene and is cooperating with the ongoing investigation.\n\n\tThe family of Cedric Benson respectfully requests privacy during this difficult time and asks that media refrain from contacting them.",
    "Time": "10:20 PM"
  }
```
to this one:
```json
{
  "Age": 36,
  "Case": "19-2291933",
  "DOB": "12/28/1982",
  "Date": "08/17/2019",
  "Ethnicity": "Black",
  "Fatal crashes this year": "50",
  "First Name": "Cedric",
  "Gender": "male",
  "ID": "19-2291933-0",
  "Last Name": "Benson",
  "Link": "http://austintexas.gov/news/traffic-fatality-50-3",
  "Location": "4500 FM 2222/Mount Bonnell Road",
  "Notes": "The preliminary investigation yielded testimony from witnesses who reported seeing the BMW motorcycle driven by Cedric Benson traveling at a high rate of speed westbound in the left lane of FM 2222. A white, 2014 Dodge van was stopped at the T-intersection of Mount Bonnell Road and FM 2222. After checking for oncoming traffic, the van attempted to turn left on to FM 2222 when it was struck by the oncoming motorcycle.\n\n The driver of the van was evaluated by EMS on scene and refused transport. The passenger of the van and a bystander at the scene attempted to render aid to Mr. Benson and his passenger Aamna Najam. Cedric Benson and Aamna Najam were both pronounced on scene.\n\n The van driver remained on scene and is cooperating with the ongoing investigation.\n\n The family of Cedric Benson respectfully requests privacy during this difficult time and asks that media refrain from contacting them.",
  "Time": "10:20 PM",
  "Other deceased": [
    {
      "Age": 27,
      "DOB": "01/26/1992",
      "Ethnicity": "Asian",
      "First Name": "Aamna",
      "Gender": "female",
      "Last Name": "Najam"
    }
  ]
}
```
then we do not need to modify the pipeline, nor the dashboard.

**Comment by mscarey** [comment]
@rgreinho:
I [made a branch](https://github.com/scrapd/scrapd/pull/188) where I tried to include all the changes from this PR without refactoring files, so it should be easier for you to see the diff.

> What's your strategy to update the pipeline and associated tooling?

Set it to use the ID field, rather than the Case field, as the key for each row of data. I don't know of any other changes that should be needed.

> What's your strategy to update the dashboard?

Set it not to display the ID field, and keep everything else the same.

About item 4, I think the "Other deceased" field would cause some difficulties because it would require you to go from rows of data to a nested data structure. I don't know how you could do CSV exports anymore if you did that. And you'd need a new visual element on the viz page to display the new field.

I really don't like scraping the city website over and over, so I haven't been running the CLI very much to see what it does. If there's an issue where ScrAPD counts only 72 entries for 2018, do you know if that's the current version of ScrAPD or the version with my updates? Is there a difference between the number of entries found by the two versions? It would really be good if the CLI would save a local copy of the pages it fetches and just work off of those once it has them. Then I could test the parser more systematically without burdening the city.

I hope I haven't misunderstood the intent of the dataviz in thinking the rows of data should represent people who died in crashes, and not crashes themselves. But I think it was clearly headed in that direction:
* The first three charts on the viz site are about "Gender", "Ethnicity", and "Age". Crashes don't have a gender, ethnicity, or age. But people do.
* The design you've chosen very prominently features the names of the people who died.
* There are many crashes where nobody dies, but those are represented nowhere on the site.

**Comment by rgreinho** [comment]
OK, super cool! Let's focus on merging the new PR first then. It will make things easier.

From your answers, I believe I found a source of confusion. The pipeline defined in https://github.com/scrapd/datasets is what I referred to in my previous comment. It is composed of importers, augmenters and the merger. By introducing a new format it is highly likely that the merger will break. If the merger breaks, there is no more data set being generated and I will receive an alert every hour until it is fixed.

Also, the merger removes duplicates (identified by case ID) to handle this use case:
* August 1st: APD published "fatality report #YY". They were missing data so it is incomplete.
* Ausgust 5th: APD got the missing information and published "fatality report #YY (update)"

This is the main script used to generate the augmented data set: https://github.com/scrapd/datasets/blob/master/tools/update-datasets.sh. You must run it locally to validate the new ScrAPD output. This process is entirely manual though, as you'll have to compare the diff between the new data set and the old one.

The nested structure certainly makes things a bit more complicated, but if we are going to make a major change anyway, we must think about it carefully.  It also does not prevent us to flatten it for the CSV export. I'll think about a it deeper today.

If you are worried for the government servers about sending 2 requests per second for 100s, you definitely ruined my faith in the public sector being able to design reliable infrastructure 😂 That being said, it will be a conversation for next time we go to Cenote 🍺  And we should involve Mateo 🍻 

Historically, the manual workflow was indeed only about crashes and the main driver. As multiple deaths in a traffic fatalities (surprisingly) only occurs a couple times a year, they had a special column for storing the extra deaths.

We do not have any information about non fatal crashes. I wanted to add it to the project, but was not able to find any public data set. So for now, we just have crashes were people die. If you are interested we could absolutely revive this idea. We'll need another round of beers 🍻 😁 

Back to the original problem here are the action items:
* Matt to finish working on the moving PR so that we can merge it and then rebase this one.
* Rémy to think about a new format
* Next: Validate the new format against the pipeline and update/fix/adjust it. After that do the same thing against the dashboard.

**Comment by rgreinho** [comment]
The Austin Data Portal is correctly counting 73 crashes and and 74 death. So there is some fishy with ScrAPD (all versions). I'll open a ticket for that.

Regarding the format, I'd like to try with this one:
```json
{
    "Case": "19-2291933",
    "Date": "08/17/2019",
    "Ethnicity": "Black",
    "Fatal crashes this year": "50",
    "Link": "http://austintexas.gov/news/traffic-fatality-50-3",
    "Location": "4500 FM 2222/Mount Bonnell Road",
    "Notes": "The preliminary investigation yielded testimony from witnesses who reported seeing the BMW motorcycle driven by Cedric Benson traveling at a high rate of speed westbound in the left lane of FM 2222. A white, 2014 Dodge van was stopped at the T-intersection of Mount Bonnell Road and FM 2222. After checking for oncoming traffic, the van attempted to turn left on to FM 2222 when it was struck by the oncoming motorcycle.\n\n The driver of the van was evaluated by EMS on scene and refused transport. The passenger of the van and a bystander at the scene attempted to render aid to Mr. Benson and his passenger Aamna Najam. Cedric Benson and Aamna Najam were both pronounced on scene.\n\n The van driver remained on scene and is cooperating with the ongoing investigation.\n\n The family of Cedric Benson respectfully requests privacy during this difficult time and asks that media refrain from contacting them.",
    "Time": "10:20 PM",
    "Deceaseds": [
        {
            "Age": 36,
            "DOB": "12/28/1982",
            "First Name": "Cedric",
            "Gender": "male",
            "Last Name": "Benson"
        },
        {
            "Age": 27,
            "DOB": "01/26/1992",
            "Ethnicity": "Asian",
            "First Name": "Aamna",
            "Gender": "female",
            "Last Name": "Najam"
        }
    ]
}
```
Deceaseds[0] would always first one reported in the list (usually the driver), the next ones will be the passengers or other people who died in the accident.

It prevents unnecessary duplication of information, and ensures that one row is one bulletin, making it easier to compare the number of bulletins and the actual number of deaths.

**Comment by mscarey** [comment]
My idea for merging records with the ID field is at https://github.com/scrapd/datasets/pull/59, and I moved my comments about caching to the Slack channel.

About changing the format, I think that changing the structure of the data that will be used as content for the dataviz is a big enough change that it would be useful to create a new PR to document it. 

With this PR the way it is, the only change to the structure of each row of data is the addition of a new unique ID column because the Case column is no longer unique. That's a smaller change because the new ID column doesn't need to be shown in the dataviz. The only visible difference in the dataviz from the work so far will be the addition of a few more rows of data for the people who previously weren't included.

**Comment by rgreinho** [comment]
> About changing the format, I think that changing the structure of the data that will be used as content for the dataviz is a big enough change that it would be useful to create a new PR to document it.
Fair point 👍 

The dashboard does not have to hide anything because it only cherry picks the fields it needs. So this part should be good for free.

However the pipeline still needs to be updated and validated. I just reviewed the other PR.

**Comment by rgreinho** [comment]
I created #190 to discuss the new format update.

Thinking about it deeper, I believe we should change the format right now instead of doing it twice. 

Keeping the format to 1 entry = 1 crash (with multiple fatalities) does not break the pipeline at all. Only the parsing of the AJAX request needs to be slightly tweaked (maybe 3 lines of code at most).

Let me know  what you think.

**Comment by mscarey** [comment]
@rgreinho you mentioned that this looks like a 50-commit PR, but the 29th commit merges the master branch, so I don't think there's any reason to look at anything before that. Sorry I left old commit history in the branch again.

I still don't think there's any easy way to just split the modules without either breaking tests or rewriting a lot of the changes in the PR. The reason for splitting the modules was because only some of the data needed to be passed to the functions in the `person` module. But I don't think that's quite how the scraper worked before this PR.

**Comment by rgreinho** [comment]
Ah OK. I'll review it like that then. 

But in the future it would be nice to try to keep the PR small (love your reviewer ❤️ 😁 ).

**Pull request merged**
